[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.18"
optimizer = true
optimizer_rounds = 200
fs_permissions = [{ access = "read", path = "./broadcast" }]

# --chains--
[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
goerli = "${RPC_GOERLI}" 
bsc = "${RPC_BSC}"
bsctest = "${RPC_BSC_TEST}"
localhost = "${RPC_LOCALHOST}"

# --scans--
[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}"}
sepolia = { key = "${ETHERSCAN_MAINNET_KEY}", chain = "11155111"}
goerli = { key = "${ETHERSCAN_MAINNET_KEY}", chain = "5" }
bsc = { key = "${BSCSCAN_KEY}", chain = "56" }
bsctest = { key = "${BSCSCAN_KEY}", chain = "97" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

